
services:
    todo-postgres:
        image: postgres
        ports:
            - 5432:5432
      
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=rahasia
            - POSTGRES_DB=belajar
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    todo-backend:
        image: ahmdy/todo-backend:v1
        ports:
            - 8080:8080
      
            
        environment:
            - DB_USER=postgres
            - DB_PASSWORD=rahasia
            - DB_HOST=todo-postgres 
            - DB_PORT=5432
            - DB_DATABASE=belajar
        depends_on:
            - todo-postgres
    todo-frontend:
        image: ahmdy/todo-frontend:v2
        ports:
          - 8081:8080
       
            
        
